### ISSUE TITLE
Change nightly build to use main branch

### ISSUE THREAD

**Issue by jsavieo** [simularium/simularium-website#352]
## What needs to happen?
We need to switch the nightly build to use the main branch rather than the released version.

We use github actions to run nightly builds. The nightly builds are published using github-pages to public websites. We need to make sure that the "main" branch is being used to create those builds, so that it picks up any merged PRs as they come in.

We also should put the nightly build url someplace discoverable, such as the readme?

QUESTION:
Key detail is that there are situations when we would like simularium-website to use simularium-viewer's main branch as well, but sometimes that may cause breakage. This probably needs to be discussed - could we have two flavors of nightly for simularium-website?

## Why should we do this?
Allows us to use merged PRs when doing new dev work without a release. 

## When does this need to get done?
By end of sprint 7/26

**Comment by toloudis** [comment]
We use github actions to run nightly builds.  The nightly builds are published using github-pages to public websites.  We need to make sure that the "main" branch is being used to create those builds, so that it picks up any merged PRs as they come in.

**Comment by blairlyons** [comment]
staging: still use released viewer
github pages: use dev head viewer

**Comment by meganrm** [comment]
Two things went wrong with this once I merged the action in and could run it:
1. The react router makes the two subdirectories a little broken. My thinking here is that we just make two repos that just host the two folders. https://simularium.github.io/simularium-website/
2. I installed the viewer using `npm i https://github.com/simularium/simularium-viewer.git`, but the repo doesn't contain any of the build artifacts (because we ignore them). I made a branch were I un-ignored the build artifacts so I could confirm that was the issue, but I think we should just publish a #dev version of the app on npm instead of using github to host the build artifacts
