### ISSUE TITLE
[Auto-conversion]-Create initial conversion form fields

### ISSUE THREAD

**Issue by meganrm** [simularium/simularium-website#395]
3 steps: choose engine, choose file, enter optional data
[Process starts here](https://xd.adobe.com/view/5f448466-eebd-4ad2-bdd8-314a55133403-0a17/screen/8449daa7-a755-4ab9-8a9d-8a547efdff60/)

- [x] Set up a ConversionFormOverlay component that is similar to ViewerOverlayTarget in that it returns null if the viewer isn't importing anything. Use similar styling to make it full screen. 
- [x] Use the VIEWER_IMPORTING state to conditionally make the appropriate  buttons in the header disabled
- [x] Use antd components to add the file import and select components

**Acceptance criteria:**
Clicking "import other file" opens a full screen overlay that takes the user through 3 steps. 
Close button does not yet need to work 
Submit button does not yet need to work 
The user can select an engine from the drop down menu. When they do it requests the required template from simulariumio 
The user can select a file to convert
The enter optional data form does not need to be functional, just the title

**Comment by meganrm** [comment]
QUESTION: where in state should this be stored? does it make more sense in `state/viewer` or in `state/selection` @frasercl it would be good to chat about this

**Comment by meganrm** [comment]
For context, here is where we described what each state branch is for: https://github.com/simularium/simularium-website/tree/main/src/state#state-branches

**Comment by interim17** [comment]
Another small template issue: The appropriate header text for submenus ("Time units", "Provide display information...") is stored in different places on the template for different parameters.

Some like "Time units" are in parameter.name, and others "Provide display information..." are in parameter.description, and text does not always match design either way.

I could render differently on a case by case basis, but it would be much cleaner to adjust template so the appropriate description is accessed in the same place for each one, and to make that text match the design. We have some other template adjustments to make like Viewport Settings being nested in Meta Data currently.

Could also just access parameter.description, in which case product would deviate from design slightly ("Provide units for time values" instead of "Time units" etc)

**Comment by meganrm** [comment]
> Another small template issue: The appropriate header text for submenus ("Time units", "Provide display information...") is stored in different places on the template for different parameters.
> 
> Some like "Time units" are in parameter.name, and others "Provide display information..." are in parameter.description, and text does not always match design either way.
> 
> I could render differently on a case by case basis, but it would be much cleaner to adjust template so the appropriate description is accessed in the same place for each one, and to make that text match the design. We have some other template adjustments to make like Viewport Settings being nested in Meta Data currently.
> 
> Could also just access parameter.description, in which case product would deviate from design slightly ("Provide units for time values" instead of "Time units" etc)

"Provide display information" is the title for the whole section of optional data. That I think can be something that is a title you have on the react side. For everything else just use parameter.name. I make an issue for Alli to update the temple to make sure the names all match.
