### ISSUE TITLE
Issues with data when another frame is requested during playback

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#421]
## Description
from @interim17: When frames are selected during playback (either by using the slider, or when looping back to the first frame) there are issues with data formatting and floats arriving when integers are expecting. Not something I can really fix on my own, so I'm going to assume we will make a separate issue/ticket for this.

Ask Joe for more info.

**Comment by ascibisz** [comment]
After talking to Joe, the issue seems that console errors appear sometimes for the simularium website when skipping to a new time in production, or when looping back to the start of a simulation in Joe's feature branch to add that functionality. There are a few different error messages that have been seen, including the following:

```
Uncaught FrontEndError: Your data is malformed, non-integer value found for num-subpoints.
```

```
Uncaught FrontEndError: Mismatch between expected num agents and parsed num agents, possible offset error
```

All of the errors associated with this bug come when parsing binary vis data messages in [VisData.ts](https://github.com/simularium/simularium-viewer/blob/main/src/simularium/VisData.ts)

After digging in, it seems like this bug exists due to the fact that when a user jumps to a new time that isn't in the local cache yet, we clear the local cache (see [here](https://github.com/simularium/simularium-viewer/blob/main/src/controller/index.ts#L280)) and then request the desired frame. Clearing the local VisData cache also clears any partial frame data that is still in the process of being read.  This isn't much of an issue, because we're jumping to a new time and we don't really care about the partially read frame that we have.  However, this will raise an error if after we clear the cache, we receive the second half of that partially read frame from the server (which hadn't yet learned that we are jumping to a new time), as the viewer doesn't know how to read a chunk of random frame data without the context of the previously received data.  For reference, VisData keeps track of previously received partial frame data [here](https://github.com/simularium/simularium-viewer/blob/main/src/simularium/VisData.ts#L480-L519), although this fails to work if the cache and `netBuffer` has been cleared.

I don't know how much we have to care about this.  Surely there's a cleaner way to handle this, but no incorrect behavior is truly happening. Hopefully, as we transition to octopus we won't need to clear the cache when jumping to a new time, I think it's just an artifact of the first timestamp weirdness that exists in simularium-engine that we're getting rid of in octopus. I don't feel particularly inclined to address this at the moment, but I'll chat with @blairlyons and @interim17 to make sure we're all on the same page.

**Comment by ascibisz** [comment]
Digging in a little further, this bug is a race condition of sorts that occurs when the exchange of messages between the client and server get into a particular state.

If the server sends a message that starts part way through a frame before receiving the new time to jump to from the client, but the client receives this message after it has already cleared `netBuffer`, then we end up in the situation where we throw a single error message and then move on.

In a more rare case, if the server sends a message that starts at the beginning of a frame and ends part way through a frame before receiving the new time to jump to from the client, we end up in a more complicated situation because the remainder portion of the message will get put in `netBuffer` and now all subsequent frames will be messed up because we are trying to tack them on to the second half of the previous message.

I'm still not confident what the best route forward is for this, but it's certainly good to think about this as we continue to work on Octopus.
